import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  generation_iv_sidebar: [{type: 'autogenerated', dirName: 'generation-iv'}],
  generation_v_sidebar: [{type: 'autogenerated', dirName: 'generation-v'}],
  universal_sidebar: [{type: 'autogenerated', dirName: 'universal'}],
};

export default sidebars;
